"""transactions table

Revision ID: 079055bd6f3d
Revises: 4650b5ccfcd3
Create Date: 2018-11-12 16:13:08.751819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079055bd6f3d'
down_revision = '4650b5ccfcd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('manual_entry_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'manual_entry_flag')
    # ### end Alembic commands ###
